title: My Page
markdown: kramdown
url: ""
baseurl: ""

# for atom feed
author:
  name: yolee
  email: yolee@student.42seoul.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  posts:
    output: true

languages: ['ja', 'ko', 'en']
default_lang: 'ko'
exclude_from_localization: ['javascript', 'images', 'css']
parallel_localization: false

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
